### ISSUE TITLE
Switching specializations fully recovering health and mana

### ISSUE THREAD

**Issue by Spydoc** [CookieMonsterDev/titans-league#33]
**Description**:

When you switch your specialization, your health and mana immediatelly get fully recovered.

**Current behaviour**:

Your health and mana get fully recovered upon changing specialization.

**Expected behaviour**:

When you switch your specialization, your health should remain with the same value, while your resource bar (mana, energy, rage and runic power) should go down to 0.

**Steps to reproduce the problem**:

Change your specialization from the talent tree menu.

**Any other useful links here**:

https://wowwiki.fandom.com/wiki/Dual_Talent_Specialization

**Update**:

After a while the +1 agility returned and now it's giving +2 agility on level 2 as expected. It seems that this isn't a permanent issue, although I've no idea how to replicate this bug and how it gets fixed.

**Comment by VincentVanclef** [comment]
This is because of the upgrade system, we have some stats that scale differently based on what spec your in. So its not a bug, ive just done so that you go back to full hp/health etc after switching spec if not in a bg/arena etc. Theres also a lot of talents that changes your total HP/mana/energy so staying at the exact same HP is not very normal either.
