### ISSUE TITLE
Item bug when grouping

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#54]
**Description**:

There seems to be a bug with your items when grouped

**Current behaviour**:

when your grouped some of your equipped gear will belong to your party member. This also makes it so when you try adding magnetics or stats to the gear the magnetics and stat gems will just dissapear and not add any stats to the gear at all due to you not owning the gear.

**Expected behaviour**:

All your gear should belong to your character and magnetics and stats should be put on the gear.

**Steps to reproduce the problem**:

Join a group at the starting zone and do the starting quests and head to a zone.

**Any other useful links here**:
https://imgur.com/a/Abo0Z8N
https://imgur.com/a/KrOk6gV

**Comment by mymanjack** [comment]
after leaving the group your gear will become yours again. seems to be an issue when in the same zone and around the other party members.

**Comment by VincentVanclef** [comment]
If you inspect someone else, you will see their stats on your gear if you share the same items. As all the starting gear is the same item underneath, your clients just sees them differently. There is a 10 second timer between inspections that resets it back to yours, unless you are still inspecting, or you can just click your portrait top left. I assure you just because you see someone elses stats doesnt change your items stats, its all visual.
