### ISSUE TITLE
Upgrading item issue

### ISSUE THREAD

**Issue by Neverlight-Jyria** [CookieMonsterDev/titans-league#82]
**Description**:

When i try to select a item and its stat i upgraded (like 41STR) It just comes up with the error "Something went wrong"
Same thing goes for upgrading the block value on the shield.

**Current behaviour**:

Not able to select max upgraded stats. When selecting for example 41STR it just hops back to the main page with the error message.

**Expected behaviour**:

When selecting a stat the next page should popup.

**Steps to reproduce the problem**:

Open the item upgrader and select a gear piece. Select the max stat and then it jumps back with the error

 **Any other useful links here**:
404 Not found

**Comment by queeb3** [comment]
Whenever I click on a stat that I've maxed out, specifically the ones that are base stats(see image 1)(as rogue those are attack power, stamina, and agility), the item upgrader seems to break and send me to an "inactive window" as I'll call it, the only difference is this new window is not called item upgrader it shares the same name as the item I was just looking at(see image 2).

I have tested this with all my addons and without all my addons turned on with the same effect.

https://gyazo.com/f81c1d9e114cda100afdfab4dd9f3c52 Image 1(this is just the normal window when looking at stats before clicking)

https://gyazo.com/d9279c2c96c1e69e3a5e9b12c61fe08f image 2(the name shows the items name instead of item upgrader)

https://gyazo.com/50d8764d8b2c056c970cda4369cbca8d Image 3(this is what is printed in chat)

I figured since it was already posted I would add some more extra info and some images to help this one along.
